### ISSUE TITLE
Uncaught referenceError

### ISSUE THREAD

**Issue by bghveding** [jamesplease/react-request#134]
Hey

Tried to use the library, but first thing I get when attemting to make a request is

`Uncaught ReferenceError: init is not defined Uncaught ReferenceError: init is not defined    at Fetch.fetchData`

https://i.imgur.com/xFTVYg5.png

Do I need to configure something?

**Comment by jamesplease** [comment]
Hi @bghveding ! Thanks for the issue. Can you post the code that you are using, and the React Request version? Thanks!

**Comment by jamesplease** [comment]
Never mind, I see the problem. I’ll release a bug fix soon.

**Comment by jamesplease** [comment]
2.0.2 will be released that fixes this in about...5minutes.

**Comment by jamesplease** [comment]
Released as 2.0.2. Thanks again for reporting the issue!

The problem here is that I recently switched to Prettier, so I disabled too many of my ESLint rules. I was thinking the eslint recommended defaults would cover all of the common sources of bugs, but I guess this particular rule isn't in that set of defaults. Now I know.

Thanks again :v:

**Comment by bghveding** [comment]
Now it works. Thanks @jamesplease :)

**Comment by jamesplease** [comment]
Glad to hear it!
