### ISSUE TITLE
ambiguous initial state

### ISSUE THREAD

**Issue by andriijas** [jamesplease/react-request#140]
Todo:
- [ ] Improve docs
<hr>
I have a `<Fetch method="post" lazy={false} />`  which seem to have an ambiguous initial state `{failed: false, fetching: false , response: null, data: null, error: null}`  which means the example code
`
      {({ fetching, failed, data }) => (
            {fetching ? (
              <Spinner />
            ) : failed ? (
              <Err />
            ) : (
              <Foo socialAd={data.foo} />
            )}
      )}
`

doesnt work because i get  `cannot read foo of null` err.

I dont have this issuewith GET requests. Im not sure whatever this is a bug or not. 

Shouldnt fetching be true initially when doing post with lazy=false? 

Thanks

**Comment by jamesplease** [comment]
I agree. Want to try your hand at a PR?

**Comment by andriijas** [comment]
Sure, just wanted to check at first.

**Comment by andriijas** [comment]
Hmm but judging from the code, fetching is always false by default for initial render and then fetching is initialized traditionally in componentDidMount. However I dont encounter this error on GETs for some reason, maybe its just luck. What's your opinion,  should children render before componentDidMount has fired?

**Comment by jamesplease** [comment]
> However I dont encounter this error on GETs for some reason, maybe its just luck.

Hmm, this seems likely.

Looking closer at your code, I wouldn't recommend the logic that you have in place. You can have `data` _and_ be `fetching` (as in the case of `cachePolicy: "cache-and-network"`. It looks like you modified the example code to use ternaries instead of if staetments, but I'm thinking that the example code I provided could be improved. It should probably check for `data` before trying to access it.

I'll probably update the example in the documentation to be this instead:

```js
if (fetching) {
  return <div>Loading data...</div>;
}

if (failed) {
  return <div>The request did not succeed.</div>;
}

if (data) {
  return (
    <div>
      <div>Post ID: {data.id}</div>
      <div>Post Title: {data.title}</div>
    </div>
  );
}

return null;
```

If you change your code to follow this logic, it should work without any issues.

---

There was a reason I made it so that `fetching` is `false` by default in that first `render`, but I forget what it was. I'd be open to changing that, too, if someone put together a PR.

**Comment by andriijas** [comment]
Lets update the docs then and keep it simple. And yeah I agree, sometimes it can be useful to refetch within some kind of interval then fetching will be true and data will be {} as well. 

Depending on the usecase it is sometimes nice to show spinner before rendering ui, and sometimes better to try to render some of the ui to give progressive touch.

Basically I already used your example as work around.

```
  {fetching ? (
              <Spinner/>
            ) : failed ? (
              <Error />
            ) : data ? (
              <BonBonLand {...data} />
            ) : null}
```


have a nice weekend!

**Comment by jamesplease** [comment]
Done! Thanks again for opening an issue! 🙂
