### ISSUE TITLE
Question: Why is it not safe to use clearRequestCache() in app code?

### ISSUE THREAD

**Issue by shanecav** [jamesplease/react-request#143]
Hi,

First off - I love this library, it's exactly what I've been looking for. Thank you for the awesome work!!

Like the title says, I'm wondering why the readme says that `clearRequestCache()` is not safe to use in application code. My use case is that all of our GET endpoints require authentication, so I'd like to clear the response cache when a user logs out.

Thanks!

**Comment by jamesplease** [comment]
Hi @shanecav ! I forget the exact reason why I added that note...I realized while writing the tests that there was a situation where you could get an uncaught exception or some other buggy behavior if you clear the cache. I didn't feel like trying to make it bullet-proof, so I added the note so that people wouldn't open issues if they started using it and it was behaving unexpectedly.

iirc it was related to clearing the cache when a request was in flight.

If you plan to use it, read through the source and see if you can spot where it could possibly cause a problem. If you make sure that situation doesn't ever happen in your app, then it should be OK!

**Comment by shanecav** [comment]
I checked out the source and can't see where it would be a problem, so I think I'm good to go. Thanks!
