### ISSUE TITLE
Question: why use fetch?

### ISSUE THREAD

**Issue by ColinRTaylor** [jamesplease/react-request#184]
Thanks for this library, love the ideas here, but I'm just curious if there were certain constraints that required you to use fetch directly, to further explain - my use case involves using an axios instance that handles a bunch of auth headers, etc. So looking for a more 'promise resolver' component

here's a rough idea: https://codesandbox.io/s/ljj0o4zv9
Not suggesting that you change this library,  just curious if you attempted something similar and hit a blocker.
Thanks!

**Comment by jamesplease** [comment]
:wave: Hi there @ColinRTaylor ! Thanks for the issue.

> if there were certain constraints that required you to use fetch directly

The requirements stem from a preference of mine to keep this library small and unopinionated. `fetch` is built into the browser, which is why I went with it over a specific http wrapper library.

When it comes to the axios wrapper specifically, that library has what I believe to be a few mistakes in their API (such as the CancelToken API), and I did not want this library to be held back by design decisions of other tools.

Everything that you can do with axios, outside of Promise-based control flow, you should be able to do with react request. The Promise-based control flow limitation just stems from the incompatibility of defining HTTP requests with JSX and Promises, rather than something to do with HTTP requests.

> So looking for a more 'promise resolver' component

That's an interesting idea! I've begun work on a new type of component that may behave more like what you are asking for, but I've paused development to wait for Suspense. tl;dr, it would be like this:

```js
<PromiseThing myPromise={myPromise}>
  {() => {}}
</PromiseThing>
```

This would allow you to make `myPromise` as complicated as it needs to be. Right now, `react-request` basically maps to a single promise, which makes serial requests difficult to do ( #59 ).

Anyway, if you're looking for something outside of configuring a `fetch` call in JSX, then that probably belongs in a separate library.

Let me know if that answers your question!

**Comment by ColinRTaylor** [comment]
@jamesplease Thanks for your answer, that makes a lot of sense.
 I attempted the promise resolver here: https://codesandbox.io/s/ljj0o4zv9
very rough but let me know if you have feedback!
I'll have to look more into Suspense, thanks for the tip.

**Comment by jamesplease** [comment]
Cool! I will definitely take a look over the next few days :v:

**Comment by jamesplease** [comment]
@ColinRTaylor , the lib you have seems cool. I don't have the time right now to give much feedback, but if its working for your use case, then that is awesome!

Since this seems unrelated to React Request, I'm going to go ahead and close out this issue. Thanks again for stoppin by and opening up an issue :)

**Comment by ColinRTaylor** [comment]
@jamesplease great, thanks for the help!
